version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/baby-django
permissions:
  - object: /home/ubuntu/baby-django
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/install_system_deps.sh
      timeout: 6000
      runas: root
    - location: scripts/install_python_deps.sh
      timeout: 6000
      runas: root
      runas: root
    - location: scripts/ngnix.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/setup_uwsgi.sh
      timeout: 6000
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: root
